name: Docker Image Deployment to Azure web app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  AZURE_WEB_APP: '<your-web-app-name>'
  DOCKER_IMAGE_NAME: 'portal_backend_api'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
